import localFont from "next/font/local";
import "./globals.css";
import { AuthUserProvider } from "./context/AuthUserContext";
import Header from "./components/Header";

const parkSans = localFont({
  src: "./fonts/Parkinsans.ttf",
  variable: "--font-park-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${parkSans.variable}`}>
        <AuthUserProvider>{children}</AuthUserProvider>
      </body>
    </html>
  );
}
